import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="tbwk-opener-vassyli", # Replace with your own username
    version="0.1.1",
    author="Basilius Sauter",
    author_email="basilius.sauter@gmail.com",
    description="An tool to open tbwk files generated by NanoDrop 2000",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Gillingham-Lab/tbwk-opener",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
    ],
    python_requires='>=3.6',
    install_requires=[
        "numpy",
        "scipy",
        "defusedxml",
    ]
)